# This is a basic workflow to help you get started with Actions

name: Build and Deploy

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the development branch
  push:
    branches: [ development ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        run: actions/checkout@development
      - name: Install dependencies
        run: npm ci
      - name: Build dependencies
        run: npm run build
      - name: Archive development aftifect
        uses: actions/upload-artifact@development
        with:
          name: dist
          path: dist
  deploy:
    name: Deploy
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        run: actions/checkout@development
      - name: Download development aftifect
        uses: actions/download-artifact@development
        with:
          name: dist
          path: dist
      - name: Deploy to Firebase
        uses: w9jds/firebase-action@development
        with:
          args: deploy --only hosting
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
