name: Build and Deploy

on:
  push:
    branches: [ development ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        run: actions/checkout@v2
      - name: Install dependencies
        run: npm ci
      - name: Build dependencies
        run: npm run build
      - name: Generate pages
        run: npm run generate  
      - name: Archive development aftifect
        uses: actions/upload-artifact@v2
        with:
          name: dist
          path: dist
  deploy:
    name: Deploy
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        run: actions/checkout@v2
      - name: Download development aftifect
        uses: actions/download-artifact@v2
        with:
          name: dist
          path: dist
      - name: Deploy to Firebase
        uses: w9jds/firebase-action@development
        with:
          args: deploy --only hosting
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
